import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Chatbot Transparency Obligations under EU AI Act | AI Engineering Wiki',
  description: 'What you need to know about chatbots and AI-generated content. Labeling requirements, disclosure, copyright — all in one place.',
}

export default function ChatbotTransparencyPage() {
  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold text-white">Chatbot Transparency Obligations</h1>
        <p className="text-slate-400 mt-2">Compliance · 4 min · Updated: Feb 2026</p>
      </div>

      <div className="prose prose-invert max-w-none">
        <div className="bg-yellow-500/10 border border-yellow-500/30 rounded-xl p-6">
          <h2 className="text-xl font-bold text-white mt-0 mb-2">For "Limited Risk" Systems</h2>
          <p className="text-slate-300 mb-0">
            Chatbots, AI-generated text/images/audio, and deepfakes fall under
            <strong> Article 50</strong>. Transparency obligations have been in effect since August 2025.
          </p>
        </div>

        <figure className="my-8">
          <img src="/images/infographics/chatbot-transparenzpflichten.png" alt="Chatbot Transparency Obligations — AI Identity, Labeling, Copyright" className="rounded-xl border border-white/10 w-full" />
          <figcaption className="text-center text-white/40 text-sm mt-2">Chatbot Transparency Obligations: What must be disclosed under Art. 50 EU AI Act</figcaption>
        </figure>

        <h2>What must be disclosed?</h2>

        <h3>1. Disclose AI Identity</h3>
        <p className="text-slate-300">
          Users must clearly and unambiguously know that they are interacting with an AI system.
        </p>
        <ul className="list-disc list-inside text-slate-300 space-y-1">
          <li>&quot;Powered by AI&quot; or &quot;AI Assistant&quot; label in the chat window</li>
          <li>For voice: announcement &quot;You are speaking with an AI system&quot;</li>
          <li>First message: notice about AI nature</li>
        </ul>

        <h3>2. Label AI-Generated Content</h3>
        <p className="text-slate-300">
          All AI-generated outputs must be identifiable as such:
        </p>
        <ul className="list-disc list-inside text-slate-300 space-y-1">
          <li>Images: &quot;AI-generated&quot; watermark or metadata</li>
          <li>Audio: &quot;AI-generated voice&quot; for text-to-speech</li>
          <li>Video: &quot;Deepfake&quot; label for synthetic videos</li>
          <li>Text: notice in footer for articles</li>
        </ul>

        <h3>3. Copyright Compliance</h3>
        <p className="text-slate-300">
          Providers of General Purpose AI (GPAI) must document:
        </p>
        <ul className="list-disc list-inside text-slate-300 space-y-1">
          <li>Which data was used for training</li>
          <li>Notify copyright holders (opt-out system)</li>
          <li>Provide a summary of training data</li>
        </ul>

        <h3>4. Prevent Deception</h3>
        <p className="text-slate-300">
          <strong>Prohibited:</strong> Designing AI systems to deceive people.
        </p>
        <ul className="list-disc list-inside text-slate-300 space-y-1">
          <li>No human-like avatars without labeling</li>
          <li>No fake reviews or ratings</li>
          <li>No manipulative design patterns</li>
        </ul>

        <h2>Checklist for Businesses</h2>
        <div className="bg-slate-900 border border-slate-700 rounded-lg p-4">
          <ul className="text-slate-300 space-y-2">
            <li>[ ] Chat interface: &quot;AI Assistant&quot; label</li>
            <li>[ ] First message: notice about AI nature</li>
            <li>[ ] AI-generated images: watermark or metadata</li>
            <li>[ ] Terms of service: notice about AI usage</li>
            <li>[ ] Privacy policy: AI processing documented</li>
            <li>[ ] Training data: copyright compliance documented</li>
            <li>[ ] Opt-out: procedure for copyright claims</li>
          </ul>
        </div>

        <h2>Examples: Good vs. Bad</h2>

        <div className="grid md:grid-cols-2 gap-4">
          <div className="bg-green-900/20 border border-green-700 rounded-lg p-4">
            <h3 className="font-semibold text-green-400 mb-2">Correct</h3>
            <ul className="text-slate-300 text-sm space-y-1">
              <li>&quot;I am an AI assistant. My answers may contain errors.&quot;</li>
              <li>AI-generated images with &quot;AI&quot; watermark</li>
              <li>Clear separation: &quot;This summary was generated by AI&quot;</li>
            </ul>
          </div>
          <div className="bg-red-900/20 border border-red-700 rounded-lg p-4">
            <h3 className="font-semibold text-red-400 mb-2">Wrong</h3>
            <ul className="text-slate-300 text-sm space-y-1">
              <li>No indication that it is a bot</li>
              <li>Realistic human avatars without labeling</li>
              <li>&quot;Customer reviews&quot; generated by AI</li>
            </ul>
          </div>
        </div>

        <h2>Implementation: AI Notice in Chatbot</h2>

        <pre className="bg-gray-900 border border-gray-700 rounded-lg p-3 mt-4 overflow-x-auto">
          <code className="text-sm text-gray-300">{`# HTML: AI notice in chat window
<div class="chat-header">
  <span class="bot-avatar">🤖</span>
  <span class="bot-name">AI Assistant</span>
  <span class="ai-badge">Powered by AI</span>
</div>

<style>
.ai-badge {
  background: #10b981;
  color: white;
  padding: 2px 8px;
  border-radius: 4px;
  font-size: 12px;
}
</style>

# Or as the first bot message:
bot_message("""
Hello! I am an AI assistant.
My answers are generated by AI and may contain errors.

For important decisions, please verify with additional sources.
""")`}</code>
        </pre>

        <h2>Penalties for Non-Compliance</h2>
        <p className="text-slate-300">
          For non-compliance with transparency obligations:
        </p>
        <ul className="list-disc list-inside text-slate-300 space-y-1">
          <li>Fines up to <strong>EUR 15 million</strong> or <strong>3% of turnover</strong></li>
          <li>Warnings from data protection authorities</li>
          <li>Reputational damage</li>
        </ul>

        <h2>Sources</h2>
        <ul>
          <li><a href="https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024R1689" target="_blank" className="text-blue-400 hover:underline">EU AI Act Original Text (EUR-Lex) — Article 50</a></li>
          <li><a href="https://www.littledata.com/eu-ai-act-compliance-checklist/" target="_blank" className="text-blue-400 hover:underline">LittleData: EU AI Act Checklist</a></li>
        </ul>
      </div>

      <div className="mt-12 pt-8 border-t border-white/10 text-center">
        <p className="text-sm text-slate-500">
          All wiki articles are free. Looking for ready-made templates and bundles?
        </p>
        <a
          href="https://www.ai-engineering.at"
          className="text-sm text-blue-400 hover:text-blue-300 transition-colors mt-2 inline-block"
        >
          View Products & Bundles →
        </a>
      </div>
    </div>
  )
}
